
// export const metadata = {
//   title: 'Contact',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body> welcome to contact page{children}</body>
//     </html>
//   )
// }
